apiVersion: v1
kind: Service
metadata:
  name: hum-ui
  namespace: default
  labels:
    run: hum-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30005
  selector:
    app: hum-ui
  type: NodePort
